### ISSUE TITLE
dvc is missing boto3

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/setup-dvc#24]
```
ERROR: failed to push data to the cloud - URL is supported but requires these missing dependencies: ['boto3']. To install dvc with those dependencies, run:

	pip install 'dvc[s3]'
```

**Comment by DavidGOrtega** [comment]
@iterative/dvc

**Comment by isidentical** [comment]
Hey @DavidGOrtega, is this happening on the latest revision? We recently fixed a similiar dependency issue in iterative/dvc/pull/5987

**Comment by DavidGOrtega** [comment]
@isidentical It seems to be the latest. The actions sets the deb package.

```
Preparing to unpack .../dvc-cml-use-cases/dvc.deb ...
Unpacking dvc (2.1.0) ...
Setting up dvc (2.1.0) ...
```

**Comment by 0x2b3bfa0** [comment]
Note: https://github.com/iterative/dvc/pull/5987 was merged 15 days ago, and [2.1.0](https://github.com/iterative/dvc/releases/tag/2.1.0) was relased 22 days ago.

**Comment by efiop** [comment]
@DavidGOrtega The error says `pip install`, so it thinks that it was installed from pip, which conflicts with your comment about `deb` package. Could you please make sure that dvc indeed installed from deb? Please check `dvc doctor`.

**Comment by casperdcl** [comment]
@efiop I presume the error message comes from https://github.com/iterative/dvc/blob/8a7ccab82fb26be7c6c6256d978c3ffa1b683a6f/dvc/fs/base.py#L100-L104 which due to a bug may be appearing even on deb pkgs?

**Comment by DavidGOrtega** [comment]
@efiop you are totally right. The error was that I forked the checkpoints repo and it was setting dvc within the requirements.txt
