### ISSUE TITLE
DVC Setup Action doesn't successfully run on Ubuntu

### ISSUE THREAD

**Issue by nepoche** [iterative/setup-dvc#43]
I am unable to integrate DVC file fetching in my CI with this action:
https://github.com/webb-tools/relayer/runs/8125894468?check_suite_focus=true

```
Run iterative/setup-dvc@v1
Error: Command failed: /usr/bin/sudo apt update && /usr/bin/sudo apt install -y --allow-downgrades git ./dvc.deb && /usr/bin/sudo rm -f 'dvc.deb'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Could not read meta data from /home/runner/work/relayer/relayer/dvc.deb
E: The package lists or status file could not be parsed or opened.
```

Maybe related to these:
https://github.com/iterative/setup-dvc/issues/39
#40

**Comment by nepoche** [comment]
It does seem to be an intermittent issue, here is another repo with similar CI configuration that passes:

https://github.com/webb-tools/protocol-solidity/runs/8125748802?check_suite_focus=true#step:4:1

**Comment by dacbd** [comment]
If you are able to reproduce this error consistently then I'll try to get a minimal example and get the error resolved.
