### ISSUE TITLE
Way to specify additional packages?

### ISSUE THREAD

**Issue by thekevinscott** [iterative/setup-dvc#51]
I'm running into a bug with DVC that may be related to a versioning issue. [One of the collaborators for DVC has asked me to install a version of DVC with a specific pinned dependency](https://github.com/iterative/dvc/issues/9653#issuecomment-1603614085), specifically, `pydrive==1.16`.

However, I don't see a way to specify additional pinned packages alongside DVC with this action. (I assume it is not possible.)

Would it be possible to support additional dependencies in this action? No worries if not as I can see that being out of scope for this action, but it sounds like future DVC consumers running into versioning issues may be asked to install specifically pinned dependencies, so thought it would be good to report.

**Comment by dacbd** [comment]
@thekevinscott there is not, the action tries to install via the `.deb` package unless it's on a Windows system.

if you require a specific set of requirements for your ci I would do the following.

```yaml
      - name: Setup Custom DVC
         run: pip install -r dvc-requirements.txt
```

where your `dvc-requirements.txt` contains the specific supporting libraries that you need, like `pydrive==1.16`

**Comment by thekevinscott** [comment]
Gotcha. That's a good idea - I'll do that. Thanks!
