### ISSUE TITLE
Updater links to a package that doesn't exist

### ISSUE THREAD

**Issue by MatthieuBizien** [iterative/setup-dvc#52]
My CI is failing, with the following logs:

```
Run iterative/setup-dvc@v1
Installing DVC from: https://dvc.org/download/linux-deb/dvc-3.5.1
DVC Download Failed, trying from GitHub Releases
Installing DVC from: https://github.com/iterative/dvc/releases/download/3.5.1/dvc_3.5.1_amd64.deb
Error: Not Found
```

The bug seems to be that https://updater.dvc.org/ currently contains `{"version": "3.5.1", "packages": {"linux": {"deb": "https://dvc.org/download/linux-deb/dvc-3.5.1", "rpm": "https://dvc.org/download/linux-rpm/dvc-3.5.1"}, "windows": {"exe": "https://dvc.org/download/win/dvc-3.5.1"}, "osx": {"pkg": "https://dvc.org/download/osx/dvc-3.5.1"}}}`, but https://dvc.org/download/linux-deb/dvc-3.5.1 does not exist.

**Comment by guillaume-michel** [comment]
Hi,
Same problem here!

**Comment by jfainberg** [comment]
This seems resolved for me now 👍

**Comment by daavoo** [comment]
The links have been updated, feel free to reopen

**Comment by johnPertoft** [comment]
This seems to keep happening. Got the same with 3.15.1.

**Comment by shcheklein** [comment]
cc @efiop

**Comment by efiop** [comment]
Our deb/rpm builds failed again https://github.com/iterative/dvc-s3-repo/actions/runs/5838306995/job/15835177156 , need to investigate. 

https://github.com/iterative/lambda-latest-version/pull/121 fixing this for now and we will make sure to wait with merging `lambda-latest-version` PRs which is where setup-dvc is getting the version from.
