### ISSUE TITLE
Support Node 20

### ISSUE THREAD

**Issue by PeterJCLaw** [iterative/setup-dvc#61]
Node 16 has reached end-of-life and GitHub have deprecated its use in Actions Runners (see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). As a result, Actions which still target Node 16 have started seeing warnings about this when run.

It would be great if this Action supported Node 20.

**Comment by shcheklein** [comment]
Please try v2 branch. Let us know if it works.
